package constant

type MediaType = string

const (
	MediaTypeJson         MediaType = "application/json"
	MediaTypeProblemJson  MediaType = "application/problem+json"
	MediaTypeForm         MediaType = "application/x-www-form-urlencoded"
	MediaTypeText         MediaType = "text/plain"
	MediaTypeHtml         MediaType = "text/html"
	MediaTypeXml          MediaType = "application/xml"
	MediaTypeYaml         MediaType = "application/x-yaml"
	MediaTypeCsv          MediaType = "text/csv"
	MediaTypeGzip         MediaType = "application/gzip"
	MediaTypePdf          MediaType = "application/pdf"
	MediaTypeDoc          MediaType = "application/msword"
	MediaTypeXls          MediaType = "application/vnd.ms-excel"
	MediaTypePpt          MediaType = "application/vnd.ms-powerpoint"
	MediaTypePng          MediaType = "image/png"
	MediaTypeJpeg         MediaType = "image/jpeg"
	MediaTypeGif          MediaType = "image/gif"
	MediaTypeSvg          MediaType = "image/svg+xml"
	MediaTypeWebp         MediaType = "image/webp"
	MediaTypeBmp          MediaType = "image/bmp"
	MediaTypeIco          MediaType = "image/x-icon"
	MediaTypeTiff         MediaType = "image/tiff"
	MediaTypeAvi          MediaType = "video/x-msvideo"
	MediaTypeMpeg         MediaType = "video/mpeg"
	MediaTypeMp4          MediaType = "video/mp4"
	MediaTypeWebm         MediaType = "video/webm"
	MediaTypeOgg          MediaType = "video/ogg"
	MediaTypeFlv          MediaType = "video/x-flv"
	MediaTypeMkv          MediaType = "video/x-matroska"
	MediaTypeWav          MediaType = "audio/wav"
	MediaTypeMp3          MediaType = "audio/mpeg"
	MediaTypeOggAudio     MediaType = "audio/ogg"
	MediaTypeFlac         MediaType = "audio/flac"
	MediaTypeAac          MediaType = "audio/aac"
	MediaTypeOpus         MediaType = "audio/opus"
	MediaTypeWebmAudio    MediaType = "audio/webm"
	MediaTypeMidi         MediaType = "audio/midi"
	MediaTypeJsonLd       MediaType = "application/ld+json"
	MediaTypeRdf          MediaType = "application/rdf+xml"
	MediaTypeAtom         MediaType = "application/atom+xml"
	MediaTypeRss          MediaType = "application/rss+xml"
	MediaTypeSoap         MediaType = "application/soap+xml"
	MediaTypeWSDL         MediaType = "application/wsdl+xml"
	MediaTypeXhtml        MediaType = "application/xhtml+xml"
	MediaTypeXforms       MediaType = "application/xforms+xml"
	MediaTypeXslt         MediaType = "application/xslt+xml"
	MediaTypeMathml       MediaType = "application/mathml+xml"
	MediaTypeOebpsPackage MediaType = "application/oebps-package+xml"
	MediaTypeOggContainer MediaType = "application/ogg"
	MediaTypeDavmount     MediaType = "application/davmount+xml"
	MediaTypeXop          MediaType = "application/xop+xml"
	MediaTypeXenc         MediaType = "application/xenc+xml"
)
